[profile.default]
libs = ["node_modules", "lib"]
src = "contracts"
out = "artifacts"
test = "tests"
cache_path = "cache"
bytecode_hash = "none"
verbosity = 3
remappings = [
  "@enzyme/=contracts/",
  "@uniswap/=node_modules/@uniswap/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@openzeppelin-solc-0.7/=node_modules/@openzeppelin-solc-0.7/",
  "forge-std/=lib/forge-std/src/"
]

[profile.default.optimizer_details]
yul = false
