name: Changeset
on:
  push:
    branches:
      - main

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  publish:
    if: github.repository == 'avantgardefinance/protocol'
    name: Publish packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.8.0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: 16

      - name: Install dependencies
        run: pnpm install

      - name: Create release pull request or publish
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm changeset:publish
          commit: 'chore: publish packages'
          title: 'chore: publish packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
